export default {
  login: 'Login',
  LOGIN: 'LOGIN',
  email: 'E-mail',
  google: 'GOOGLE',
  signUp: 'Sign Up',
  SIGNUP: 'SIGN UP',
  password: 'Password',
  fullName: 'Full Name',
  welcomeTo: 'Welcome to',
  signUpWith: 'Sign up with',
  signInWith: 'Sign in with',
  corporatefood: 'Corporate Food',
  loginWithEmail: 'Login with Email',
  forgotPassword: 'Forgot password?',
  emailPlaceHolder: 'Your email or phone',
  dontHaveAccount: 'Don’t have an account? ',
  alreadyHaveAccount: 'Already have an account? ',
};
